platform :ios, '13.0'

target 'AccountDetailBank' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AccountDetailBank

 pod 'Alamofire', '~> 5.4.3'

end
